# Generated by Django 5.1.3 on 2024-11-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_remove_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='name',
        ),
    ]
