# Generated by Django 5.1.3 on 2024-12-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('insurance_number', models.CharField(max_length=15, unique=True)),
                ('carrier_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=15, unique=True)),
                ('invoice_date', models.DateField()),
                ('service_id', models.CharField(max_length=15)),
                ('service_description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_billed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.patient')),
            ],
        ),
    ]
