# Generated by Django 5.1.3 on 2024-12-10 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_carrier_service_remove_billing_service_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='service',
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='cost',
            new_name='amount_billed',
        ),
        migrations.RenameField(
            model_name='billing',
            old_name='invoice_date',
            new_name='date_of_service',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='total_billed',
        ),
        migrations.RemoveField(
            model_name='carrier',
            name='payment_reliability',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='carrier',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='billing',
            name='carrier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='insurance.carrier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='service_id',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrier',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='insurance.billing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=5, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='insurance.patient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='service_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='carrier',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='insurance.carrier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='insurance_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
