# Generated by Django 5.1.3 on 2024-12-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_rename_billing_invoice_billings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='billings',
        ),
        migrations.AddField(
            model_name='invoice',
            name='billings',
            field=models.ManyToManyField(related_name='invoices', to='insurance.billing'),
        ),
    ]
