# Generated by Django 5.1.3 on 2024-11-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='signature',
            field=models.CharField(max_length=255),
        ),
    ]
