# Generated by Django 5.1.1 on 2024-12-07 05:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "employeeid",
                    models.AutoField(
                        db_column="EmployeeID", primary_key=True, serialize=False
                    ),
                ),
                ("firstname", models.CharField(db_column="FirstName", max_length=45)),
                ("lastname", models.CharField(db_column="LastName", max_length=45)),
                ("title", models.CharField(db_column="Title", max_length=20)),
                (
                    "phonenumber",
                    models.CharField(db_column="PhoneNumber", max_length=15),
                ),
                ("workdays", models.CharField(db_column="WorkDays", max_length=20)),
            ],
            options={
                "db_table": "employees",
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "equipmentid",
                    models.IntegerField(
                        db_column="EquipmentID", primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(db_column="Type", max_length=45)),
                (
                    "lease_terms",
                    models.CharField(
                        blank=True, db_column="Lease Terms", max_length=45, null=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=120, null=True
                    ),
                ),
                (
                    "departmentleased",
                    models.CharField(
                        blank=True,
                        db_column="DepartmentLeased",
                        max_length=45,
                        null=True,
                    ),
                ),
                (
                    "owned_lease",
                    models.CharField(db_column="Owned/Lease", max_length=1),
                ),
                (
                    "purchasedate",
                    models.DateField(blank=True, db_column="PurchaseDate", null=True),
                ),
                (
                    "warenty_info",
                    models.CharField(
                        blank=True, db_column="Warenty Info", max_length=120, null=True
                    ),
                ),
            ],
            options={
                "db_table": "equipment",
            },
        ),
        migrations.CreateModel(
            name="Insurance",
            fields=[
                (
                    "carrierid",
                    models.AutoField(
                        db_column="CarrierID", primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(db_column="Name", max_length=20)),
                ("address", models.CharField(db_column="Address", max_length=45)),
                ("status", models.CharField(db_column="Status", max_length=120)),
            ],
            options={
                "db_table": "insurance",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "lineitemid",
                    models.AutoField(
                        db_column="LineItemID", primary_key=True, serialize=False
                    ),
                ),
                ("status", models.CharField(db_column="Status", max_length=120)),
            ],
            options={
                "db_table": "invoice",
            },
        ),
        migrations.CreateModel(
            name="LabTests",
            fields=[
                (
                    "typeid",
                    models.AutoField(
                        db_column="TypeID", primary_key=True, serialize=False
                    ),
                ),
                ("typename", models.CharField(db_column="TypeName", max_length=20)),
                (
                    "normalrange",
                    models.CharField(db_column="NormalRange", max_length=10),
                ),
                (
                    "urgentrange",
                    models.CharField(db_column="UrgentRange", max_length=10),
                ),
            ],
            options={
                "db_table": "lab tests",
                "db_table_comment": "\\n\\n\\n",
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "medicationid",
                    models.IntegerField(
                        db_column="MedicationID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "medicationname",
                    models.CharField(db_column="MedicationName", max_length=20),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=120, null=True
                    ),
                ),
                ("recdosage", models.CharField(db_column="RecDosage", max_length=120)),
                ("recfreq", models.CharField(db_column="RecFreq", max_length=120)),
                (
                    "sideeffects",
                    models.CharField(db_column="SideEffects", max_length=120),
                ),
                (
                    "adversedrugs",
                    models.CharField(db_column="AdverseDrugs", max_length=120),
                ),
            ],
            options={
                "db_table": "medication",
            },
        ),
        migrations.CreateModel(
            name="ProblemType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField()),
                (
                    "equipment_types",
                    models.CharField(
                        help_text="Comma-separated list of equipment types",
                        max_length=200,
                    ),
                ),
                ("preferred", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="PatientRecord",
            fields=[
                (
                    "patientid",
                    models.AutoField(
                        db_column="PatientID", primary_key=True, serialize=False
                    ),
                ),
                ("firstname", models.CharField(db_column="FirstName", max_length=20)),
                ("lastname", models.CharField(db_column="LastName", max_length=20)),
                (
                    "phonenumber",
                    models.CharField(db_column="PhoneNumber", max_length=15),
                ),
                ("address", models.CharField(db_column="Address", max_length=45)),
                ("dob", models.DateField(db_column="DOB")),
                ("gender", models.CharField(db_column="Gender", max_length=1)),
                (
                    "medications",
                    models.CharField(
                        blank=True, db_column="Medications", max_length=45, null=True
                    ),
                ),
                (
                    "insuranceid",
                    models.ForeignKey(
                        db_column="InsuranceID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.insurance",
                    ),
                ),
                (
                    "primaryphysicianid",
                    models.ForeignKey(
                        db_column="PrimaryPhysicianID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.employees",
                    ),
                ),
            ],
            options={
                "db_table": "patient record",
            },
        ),
        migrations.CreateModel(
            name="LabOrders",
            fields=[
                (
                    "orderid",
                    models.AutoField(
                        db_column="OrderID", primary_key=True, serialize=False
                    ),
                ),
                ("results", models.IntegerField(db_column="Results")),
                (
                    "dateperfomed",
                    models.DateTimeField(db_column="Dateperfomed", null=True),
                ),
                (
                    "dateordered",
                    models.DateTimeField(db_column="Dateordered", null=True),
                ),
                (
                    "physicianid",
                    models.ForeignKey(
                        db_column="PhysicianID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.employees",
                    ),
                ),
                (
                    "technicianid",
                    models.ForeignKey(
                        db_column="TechnicianID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="laborders_technicianid_set",
                        to="sharedModels.employees",
                    ),
                ),
                (
                    "teststypeid",
                    models.ForeignKey(
                        db_column="TestsTypeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.labtests",
                    ),
                ),
                (
                    "patientid",
                    models.ForeignKey(
                        db_column="PatientID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.patientrecord",
                    ),
                ),
            ],
            options={
                "db_table": "lab orders",
            },
        ),
        migrations.CreateModel(
            name="Appointments",
            fields=[
                (
                    "appointmentid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(db_column="Date")),
                ("enddate", models.DateTimeField(db_column="enddate", null=True)),
                (
                    "aptType",
                    models.CharField(
                        choices=[
                            ("routine", "Routine"),
                            ("urgent_care", "Urgent Care"),
                            ("follow_up_visit", "Follow-Up Visit"),
                            ("N/A", "N/A"),
                        ],
                        default="N/A",
                        max_length=20,
                    ),
                ),
                (
                    "physcianid",
                    models.ForeignKey(
                        db_column="PhyscianID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.employees",
                    ),
                ),
                (
                    "patientid",
                    models.ForeignKey(
                        db_column="PatientID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.patientrecord",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
            },
        ),
        migrations.CreateModel(
            name="PharmacyOrder",
            fields=[
                (
                    "prescriptionid",
                    models.IntegerField(
                        db_column="PrescriptionID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        blank=True, db_column="Dosage", max_length=45, null=True
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, db_column="Frequency", max_length=45, null=True
                    ),
                ),
                ("date", models.DateField(blank=True, db_column="Date", null=True)),
                (
                    "pharmacist",
                    models.CharField(
                        blank=True, db_column="Pharmacist", max_length=45, null=True
                    ),
                ),
                (
                    "medicationid",
                    models.ForeignKey(
                        db_column="MedicationID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.medication",
                    ),
                ),
                (
                    "patientid",
                    models.ForeignKey(
                        db_column="PatientID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.patientrecord",
                    ),
                ),
                (
                    "physicianid",
                    models.ForeignKey(
                        db_column="PhysicianID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.employees",
                    ),
                ),
            ],
            options={
                "db_table": "pharmacy order",
            },
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "serviceid",
                    models.AutoField(
                        db_column="ServiceID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=120, null=True
                    ),
                ),
                ("cost", models.FloatField(db_column="Cost")),
            ],
            options={
                "db_table": "services",
                "unique_together": {("serviceid", "cost")},
            },
        ),
        migrations.CreateModel(
            name="Maintenance",
            fields=[
                (
                    "maintenanceid",
                    models.IntegerField(
                        db_column="MaintenanceID", primary_key=True, serialize=False
                    ),
                ),
                ("type", models.CharField(db_column="Type", max_length=45)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_column="Description", max_length=120, null=True
                    ),
                ),
                ("status", models.CharField(db_column="Status", max_length=45)),
                (
                    "resolution",
                    models.CharField(
                        blank=True, db_column="Resolution", max_length=120, null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_column="CreatedAt", default=django.utils.timezone.now
                    ),
                ),
                (
                    "equipmentid",
                    models.ForeignKey(
                        db_column="EquipmentID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.equipment",
                    ),
                ),
            ],
            options={
                "db_table": "maintenance",
                "unique_together": {("maintenanceid", "equipmentid")},
            },
        ),
        migrations.CreateModel(
            name="Encounters",
            fields=[
                (
                    "encounterid",
                    models.AutoField(
                        db_column="EncounterID",
                        default=0,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateTimeField(db_column="Date")),
                (
                    "patientcomplaints",
                    models.CharField(
                        blank=True,
                        db_column="PatientComplaints",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "vitalsigns",
                    models.CharField(
                        blank=True, db_column="VitalSigns", max_length=120, null=True
                    ),
                ),
                (
                    "practitionernotes",
                    models.CharField(
                        blank=True,
                        db_column="PractitionerNotes",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "treatment_plan",
                    models.CharField(
                        blank=True,
                        db_column="Treatment Plan",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "refferals",
                    models.CharField(
                        blank=True, db_column="Refferals", max_length=120, null=True
                    ),
                ),
                (
                    "recfollowup",
                    models.DateField(blank=True, db_column="RecFollowUp", null=True),
                ),
                (
                    "physicianid",
                    models.ForeignKey(
                        db_column="PhysicianID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.employees",
                    ),
                ),
                (
                    "laborderid",
                    models.ForeignKey(
                        db_column="LabOrderID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.laborders",
                    ),
                ),
                (
                    "patientid",
                    models.ForeignKey(
                        db_column="PatientID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.patientrecord",
                    ),
                ),
                (
                    "pharmacyorderid",
                    models.ForeignKey(
                        db_column="PharmacyOrderID",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.pharmacyorder",
                    ),
                ),
            ],
            options={
                "db_table": "encounters",
                "unique_together": {("date", "physicianid")},
            },
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "username",
                    models.CharField(
                        db_column="Username",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, db_column="Title", max_length=20, null=True
                    ),
                ),
                ("password", models.CharField(db_column="Password", max_length=30)),
                ("firstname", models.CharField(db_column="FirstName", max_length=20)),
                ("lastname", models.CharField(db_column="LastName", max_length=20)),
                (
                    "employeeid",
                    models.ForeignKey(
                        db_column="EmployeeID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="sharedModels.employees",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "db_table_comment": "\t",
                "unique_together": {("username", "employeeid")},
            },
        ),
    ]
