# Generated by Django 5.1.1 on 2024-11-06 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharedModels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="appointmentid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
