# Generated by Django 5.1.1 on 2024-11-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharedModels", "0002_alter_appointments_appointmentid"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointments",
            name="enddate",
            field=models.DateTimeField(db_column="enddate", null=True),
        ),
    ]
