# Generated by Django 5.1.1 on 2024-12-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharedModels", "0002_appointments_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="description",
            field=models.TextField(default="N/A", max_length=500),
        ),
        migrations.AlterField(
            model_name="encounters",
            name="encounterid",
            field=models.AutoField(
                db_column="EncounterID", primary_key=True, serialize=False
            ),
        ),
    ]
