# Generated by Django 5.1.1 on 2024-11-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sharedModels", "0003_appointments_enddate"),
    ]

    operations = [
        migrations.AddField(
            model_name="laborders",
            name="dateordered",
            field=models.DateTimeField(db_column="Dateordered", null=True),
        ),
        migrations.AddField(
            model_name="laborders",
            name="dateperfomed",
            field=models.DateTimeField(db_column="Dateperfomed", null=True),
        ),
    ]
