# Generated by Django 5.1.3 on 2024-12-06 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedModels', '0004_laborders_dateordered_laborders_dateperfomed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField()),
                ('equipment_types', models.CharField(help_text='Comma-separated list of equipment types', max_length=200)),
                ('preferred', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='encounters',
            name='encounterid',
            field=models.AutoField(db_column='EncounterID', default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(db_column='CreatedAt', default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='date',
            field=models.DateTimeField(db_column='Date'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='laborderid',
            field=models.ForeignKey(db_column='LabOrderID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sharedModels.laborders'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='pharmacyorderid',
            field=models.ForeignKey(db_column='PharmacyOrderID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sharedModels.pharmacyorder'),
        ),
    ]
