# Generated by Django 5.1.2 on 2024-12-06 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_lease_end_equipment_lease_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='vendor',
            field=models.ForeignKey(blank=True, db_column='VendorID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipment.vendor'),
        ),
    ]
