# Generated by Django 5.1.2 on 2024-12-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_equipment_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_column='ClosedAt', null=True),
        ),
    ]
