# Generated by Django 5.1.1 on 2024-12-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0005_maintenance_closed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maintenance",
            name="maintenanceid",
            field=models.AutoField(
                db_column="MaintenanceID", primary_key=True, serialize=False
            ),
        ),
    ]
